apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v07m6dvvl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v07m6dvvl-nodejs 
  name: v07m6dvvl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: v07m6dvvl-nodejs 
